import Link from "next/link";
import { ArrowRight, BookOpen, CalendarDays, HeartHandshake, ShieldCheck, Users, Megaphone } from "lucide-react";

const rights = [
  [ShieldCheck, "Protection", "Every child deserves safety, dignity and protection from abuse and exploitation."],
  [BookOpen, "Education", "Learn about your rights and access information that helps you thrive."],
  [HeartHandshake, "Participation", "Your views matter. Children should be heard in decisions affecting their lives."],
  [Users, "Leadership", "Build confidence, civic knowledge and leadership skills through the Assembly."],
];

export default function Home() {
  return <main>
    <section className="overflow-hidden bg-[linear-gradient(135deg,#003b24_0%,#006b3f_60%,#0a8b57_100%)] text-white">
      <div className="container-page grid min-h-[680px] items-center gap-12 py-20 lg:grid-cols-[1.1fr_.9fr]">
        <div>
          <div className="mb-6 inline-flex rounded-full border border-white/20 bg-white/10 px-4 py-2 text-sm font-semibold backdrop-blur">🇰🇪 Sauti Yako • Your Voice</div>
          <h1 className="max-w-4xl text-5xl font-black tracking-tight sm:text-6xl lg:text-7xl">Children belong at the table where their future is shaped.</h1>
          <p className="mt-7 max-w-2xl text-lg leading-8 text-white/80">The Kenya Children Assembly is a platform for children to understand their rights, develop leadership and make their voices heard.</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="#assembly" className="inline-flex items-center justify-center gap-2 rounded-full bg-white px-6 py-3.5 font-bold text-[var(--green)]">Explore the Assembly <ArrowRight size={18}/></Link><Link href="#rights" className="inline-flex items-center justify-center rounded-full border border-white/30 px-6 py-3.5 font-bold">Know your rights</Link></div>
        </div>
        <div className="relative"><div className="absolute -inset-10 rounded-full bg-[var(--gold)]/20 blur-3xl"/><div className="relative rounded-[32px] border border-white/15 bg-white/10 p-8 shadow-2xl backdrop-blur-xl"><div className="mb-8 flex items-center justify-between"><span className="font-bold">Assembly at a glance</span><span className="rounded-full bg-[var(--gold)] px-3 py-1 text-xs font-black text-black">LIVE PLATFORM</span></div><div className="grid grid-cols-2 gap-4">{[["47", "Counties"],["18", "Years & below"],["1", "National voice"],["∞", "Ideas welcome"]].map(([n,l]) => <div key={l} className="rounded-2xl bg-black/15 p-5"><div className="text-3xl font-black">{n}</div><div className="mt-1 text-sm text-white/70">{l}</div></div>)}</div><div className="mt-4 rounded-2xl bg-white p-5 text-[var(--ink)]"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-full bg-[#e7f5ed]"><Megaphone size={19} className="text-[var(--green)]"/></div><div><div className="font-bold">Your voice matters</div><div className="text-sm text-slate-500">Learn, participate, lead.</div></div></div></div></div></div>
      </div>
    </section>

    <section id="about" className="section"><div className="container-page grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow">About the Assembly</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">A digital home for children's participation.</h2></div><div><p className="text-lg leading-8 text-slate-600">The Assembly creates space for children to engage with leadership, civic life and child-rights advocacy. This platform is designed to make that information easier to discover on any device.</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><div className="card p-5"><CalendarDays className="text-[var(--green)]"/><p className="mt-3 font-bold">Events & activities</p></div><div className="card p-5"><Users className="text-[var(--red)]"/><p className="mt-3 font-bold">Children's leadership</p></div></div></div></div></section>

    <section id="rights" className="section bg-white"><div className="container-page"><p className="eyebrow">Know your rights</p><h2 className="mt-3 text-4xl font-black tracking-tight">Your rights. Your protection. Your voice.</h2><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{rights.map(([Icon,title,desc]) => { const I = Icon as typeof ShieldCheck; return <article key={title as string} className="card p-6 transition hover:-translate-y-1"><div className="grid size-12 place-items-center rounded-2xl bg-[#eaf7f0] text-[var(--green)]"><I/></div><h3 className="mt-5 text-xl font-extrabold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{desc as string}</p></article>})}</div></div></section>

    <section id="assembly" className="section"><div className="container-page grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-[28px] bg-[var(--green)] p-8 text-white"><p className="text-sm font-bold uppercase tracking-widest text-[#b8e7d0]">The Assembly</p><h2 className="mt-3 text-4xl font-black">Learn. Debate. Lead.</h2><p className="mt-4 leading-7 text-white/75">Discover how children's assemblies can create practical spaces for representation, dialogue and action.</p><Link href="#resources" className="mt-7 inline-flex items-center gap-2 font-bold">Explore resources <ArrowRight size={18}/></Link></div><div className="grid gap-5 sm:grid-cols-3"><div className="card p-6"><div className="text-3xl font-black text-[var(--green)]">01</div><h3 className="mt-5 font-extrabold">Represent</h3><p className="mt-2 text-sm text-slate-500">Bring children's experiences and ideas forward.</p></div><div className="card p-6"><div className="text-3xl font-black text-[var(--red)]">02</div><h3 className="mt-5 font-extrabold">Discuss</h3><p className="mt-2 text-sm text-slate-500">Engage in respectful dialogue around issues that matter.</p></div><div className="card p-6"><div className="text-3xl font-black text-[#c88a00]">03</div><h3 className="mt-5 font-extrabold">Act</h3><p className="mt-2 text-sm text-slate-500">Turn ideas into positive action with trusted adults.</p></div></div></div></section>

    <section id="resources" className="section bg-[#0b1f17] text-white"><div className="container-page flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-bold uppercase tracking-widest text-[#9fe0bd]">Resources</p><h2 className="mt-3 text-4xl font-black">A better way to find help and information.</h2><p className="mt-4 max-w-2xl leading-7 text-white/65">The next phase can connect this experience to verified child-protection resources, Assembly updates, events and a secure reporting workflow.</p></div><Link href="#report" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-full bg-[var(--gold)] px-6 py-3.5 font-bold text-black">Speak up <ArrowRight size={18}/></Link></div></section>

    <section id="report" className="section"><div className="container-page"><div className="card grid overflow-hidden lg:grid-cols-[.9fr_1.1fr]"><div className="bg-[var(--red)] p-8 text-white"><h2 className="text-3xl font-black">Need help or want to speak up?</h2><p className="mt-4 leading-7 text-white/80">This interface is prepared for a future verified reporting backend. Do not submit sensitive personal information until that workflow is connected and clearly identified.</p></div><form className="p-8" onSubmit={(e)=>e.preventDefault()}><label className="block text-sm font-bold">What would you like to share?</label><textarea className="mt-2 min-h-36 w-full rounded-2xl border border-slate-200 p-4 outline-none focus:border-[var(--green)]" placeholder="Your message..."/><button className="mt-4 w-full rounded-2xl bg-[var(--green)] px-5 py-3.5 font-bold text-white">Continue safely</button><p className="mt-3 text-xs text-slate-400">Demo interface — no report is transmitted.</p></form></div></div></section>

    <footer className="border-t bg-white py-8"><div className="container-page flex flex-col gap-3 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span>© {new Date().getFullYear()} Kenya Children Assembly</span><span>Built for children. Designed for participation.</span></div></footer>
  </main>;
}
